config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :meetings, :all_meetings, :user_meetings do
    collection do
      get 'day_calendar'
      get 'list'
    end
  end

  get 'users/:id', to: 'users#show', as: 'user_show'
  root 'all_meetings#index'
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	belongs_to :user
	validates :name, presence: true
	validates :start_time, presence: true
	validate :start_must_be_before_end_time

    private

      def start_must_be_before_end_time
      	if (start_time != nil && end_time != nil)
          errors.add(:start_time, "must be before end time") unless
            start_time <= end_time
        end
      end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :meetings, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/all_meetings_controller.rb
class AllMeetingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = Meeting.all
  end

  def show
  end

  def day_calendar
    @meetings = Meeting.all
  end

  def list
    @meetings = Meeting.all.order(start_time: :desc).page(params[:page]).per(10)
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :place, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    user_params = [:first_name, :second_name, :email, :password, :password_confirmation, :avatar, :avatar_cache,
    :sex, :birthday, :phone_number, :country, :city]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(user_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(user_params) 
      }
    end
  end

  def set_time_zone
    Time.zone = current_user.time_zone
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = current_user.meetings
  end

  def show
  end

  def day_calendar
    @meetings = current_user.meetings
  end

  def list
    @meetings = current_user.meetings.order(start_time: :desc).page(params[:page]).per(10)
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    @meeting = current_user.meetings.create(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_path(@meeting), notice: 'Meeting was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
    end
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :place, :description, :avatar)
    end
end

app/controllers/user_meetings_controller.rb
class UserMeetingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find(params[:id])
    @meetings = @user.meetings
  end

  def day_calendar
    @user = User.find(params[:id])
    @meetings = @user.meetings
  end

  def list
    @user = User.find(params[:id])
    @meetings = @user.meetings.order(start_time: :desc).page(params[:page]).per(10)
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :place, :description, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
    
  def edit
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update(user_params)
      sign_in @user, bypass: true
      redirect_to root_path
    else
      render "edit"
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/all_meetings_helper.rb
module AllMeetingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/user_meetings_helper.rb
module UserMeetingsHelper
end

app/views/all_meetings/day_calendar.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = calendar number_of_days: 1, events: @meetings do |date, meetings|
      - if date == Date.today
        .text-red
          = date.strftime("%d")
          |  
          = date.strftime("%B")
          |  
          = date.strftime("%Y")
          br
          h4.font-weight-200.padding-top-8
            = date.strftime('%A')
      - else
        = date.strftime("%d")
        |  
        = date.strftime("%B")
        |  
        = date.strftime("%Y")
        br
        h4.font-weight-200
          = date.strftime('%A')
      
      ul.text-black
        br
        - for meeting in meetings
          h3
            .text-center
              = link_to meeting.name, meeting_path(meeting)
          table.white-borders.text-left
            tr.white-borders
              td.width-100
                | Start time:
              td = meeting.start_time.strftime("%d.%m.%Y")
            - if meeting.end_time != nil
              tr.white-borders
                td.width-100
                  | End time:
                td = meeting.end_time.strftime("%d.%m.%Y")
            - if meeting.place != '' && meeting.place != nil
              tr.white-borders
                td.width-100 valign="top"
                  | Place:
                td = truncate(meeting.place, length: 90, separator: ' ')
            - if meeting.description != ''
              tr.white-borders
                td.width-100 valign="top"
                  | Description:
                td = truncate(meeting.description, length: 90, separator: ' ')
            tr.white-borders
              td.width-100 valign="top"
                | Autor:
              td
                dfn
                  = link_to meeting.user.email, user_show_path(meeting.user)
          .text-center
            = link_to "Show", meeting_path(meeting), class: "hollow button"
          hr
          br
        - if meetings.empty?
          h5.text-center.font-weight-200
            | No events
      h4.font-weight-200
        i
          = link_to "Create event on this day", new_meeting_path(start_date: date.strftime("%d.%m.%Y"))

  .small-2.columns
    h4.text-center.font-weight-200
      | All events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", all_meetings_path
      br
      .font-weight-300 
        = link_to "Day calendar", day_calendar_all_meetings_path
      = link_to "List", list_all_meetings_path
      hr
      = link_to "Today", day_calendar_all_meetings_path

app/views/all_meetings/index.html.slim
== yield

.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = month_calendar events: @meetings do |date, meetings|
      .text-right
        - if date == Date.today
          = link_to date.strftime("%d"), day_calendar_all_meetings_path(start_date: date.strftime("%Y-%m-%d")), {style: 'color: red'}
        - else
          = link_to date.strftime("%d"), day_calendar_all_meetings_path(start_date: date.strftime("%Y-%m-%d"))

      
      ul
        .text-black
          - if meetings != nil
            - for meeting in meetings
              - if meeting.user_id == current_user.id
                li
                  = link_to truncate(meeting.name, length: 9, separator: ' '), {controller: "meetings", action: "show", id: meeting.id}
              - else
                li
                  = link_to truncate(meeting.name, length: 9, separator: ' '), all_meeting_path(meeting)
  .small-2.columns
    h4.text-center.font-weight-200
      | All events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200
      .font-weight-300 
        = link_to "Month calendar", all_meetings_path
      = link_to "Day calendar", day_calendar_all_meetings_path
      br
      = link_to "List", list_all_meetings_path
      hr
      = link_to "Today", all_meetings_path

app/views/all_meetings/list.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    - for meeting in @meetings
      - if params[:today_events] == 'true'
        - if meeting.start_time == Date.today
          h3.text-center
            - if meeting.user_id == current_user.id
              = link_to meeting.name, {controller: "meetings", action: "show", id: meeting.id}
            - else
              = link_to meeting.name, all_meeting_path(meeting)
          table.white-borders
              tr
                td.width-100
                  | Start time:
                td = meeting.start_time.strftime("%d.%m.%Y")
              - if meeting.end_time != nil
                tr
                  td.width-100
                    | End time:
                  td = meeting.end_time.strftime("%d.%m.%Y")
              - if meeting.place != '' && meeting.place != nil
                tr
                  td.width-100 valign="top"
                    | Place:
                  td = truncate(meeting.place, length: 90, separator: ' ')
              - if meeting.description != ''
                tr
                  td.width-100 valign="top"
                    | Description:
                  td = truncate(meeting.description, length: 90, separator: ' ')
              tr
                td.width-100 valign="top"
                  | Autor:
                td
                  dfn
                    = link_to meeting.user.email, user_show_path(meeting.user)
          hr

      - else
        h3.text-center
          - if meeting.user_id == current_user.id
            = link_to meeting.name, {controller: "meetings", action: "show", id: meeting.id}
          - else
            = link_to meeting.name, all_meeting_path(meeting)
        table.white-borders
          tr
            td.width-100
              | Start time:
            td = meeting.start_time.strftime("%d.%m.%Y")
          - if meeting.end_time != nil
            tr
              td.width-100
                | End time:
              td = meeting.end_time.strftime("%d.%m.%Y")
          - if meeting.place != '' && meeting.place != nil
            tr
              td.width-100 valign="top"
                | Place:
              td = truncate(meeting.place, length: 90, separator: ' ')
          - if meeting.description != ''
            tr
              td.width-100 valign="top"
                | Description:
              td = truncate(meeting.description, length: 90, separator: ' ')
          tr
            td.width-100 valign="top"
              | Autor:
            td
              dfn
                = link_to meeting.user.email, user_show_path(meeting.user)
        hr

    = paginate @meetings
    - if @meetings.empty?
      h2.text-center
        | All events
      h3.text-center
        br
          | No events. You can  
          dfn
            = link_to "create", new_meeting_path
          |  an event first

  .small-2.columns
    h4.text-center.font-weight-200
      | All events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", all_meetings_path
      br
      = link_to "Day calendar", day_calendar_all_meetings_path
      .font-weight-300 
        = link_to "List", list_all_meetings_path
      hr
      - if params[:today_events] == 'true'
        = link_to "All events", list_all_meetings_path(today_events: false)
      - else
        = link_to "Events today", list_all_meetings_path(today_events: true)

app/views/all_meetings/show.html.slim
.row
  .small-6.small-offset-3.columns
    div id="notice"
      = notice

    h2
      .text-center
        = @meeting.name
    table.white-borders
      tr
        td.width-100
          | Start time:
        td = @meeting.start_time.strftime("%d.%m.%Y")
      - if @meeting.end_time != nil
        tr
          td.width-100
            | End time:
          td = @meeting.end_time.strftime("%d.%m.%Y")
      - if @meeting.place != '' && @meeting.place != nil
        tr
          td.width-100 valign="top"
            | Place:
          td = @meeting.place
      - if @meeting.description != ''
        tr
          td.width-100 valign="top"
            | Description:
          td = @meeting.description
      tr
        td.width-100 valign="top"
          | Autor:
        td
          dfn
            = link_to @meeting.user.email, user_show_path(@meeting.user)
    br
    .text-center
      = link_to 'Back', :back , class: "hollow button"

app/views/application/_navigation.html.slim
.top-bar
  div id='responsive-menu'
    = render 'navigation_user'
    = render 'navigation_main'

app/views/application/_navigation_main.html.slim
.top-bar-left
  .padding-left-5
    .top-bar-title
      h3
        .menu-text
          .font-weight-300
            = link_to "Calendar", root_path
.top-bar-right
  ul.menu

hr

app/views/application/_navigation_user.html.slim
.top-bar-right
  .padding-right-20
    - if user_signed_in?
      ul.dropdown.menu data-dropdown-menu=""
        li.nav-bar-1
          h6
            = link_to "Create event", new_meeting_path
        li.nav-bar-1
          h6 = link_to "All events", all_meetings_path
          ul.menu.vertical
            li.nav-bar-2
              h6 = link_to "Month calendar", all_meetings_path
            li.nav-bar-3
              h6 = link_to "Day calendar", day_calendar_all_meetings_path
            li.nav-bar-3
              h6 = link_to "List", list_all_meetings_path
        li.nav-bar-1
          h6 = link_to "My events", meetings_path
          ul.menu.vertical
            li.nav-bar-2
              h6 = link_to "Month calendar", meetings_path
            li.nav-bar-3
              h6 = link_to "Day calendar", day_calendar_meetings_path
            li.nav-bar-3
              h6 = link_to "List", list_meetings_path
        li.nav-bar-1
          h6 = link_to current_user.email, user_show_path(current_user.id)
          ul.menu.vertical
            li.nav-bar-2
              h6 = link_to "My profile", user_show_path(current_user.id)
            li.nav-bar-3
              h6 = link_to "Edit profile", edit_user_registration_path
            li.nav-bar-3
              h6 = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      ul.dropdown.menu data-dropdown-menu=""
        li.nav-bar-1
          h6 = link_to "Sign in", new_user_session_path
        li.nav-bar-1
          h6 = link_to "Sign up", new_user_registration_path

app/views/meetings/day_calendar.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = calendar number_of_days: 1, events: @meetings do |date, meetings|
      - if date == Date.today
        .text-red
          = date.strftime("%d")
          |  
          = date.strftime("%B")
          |  
          = date.strftime("%Y")
          br
          h4.font-weight-200.padding-top-8
            = date.strftime('%A')
      - else
        = date.strftime("%d")
        |  
        = date.strftime("%B")
        |  
        = date.strftime("%Y")
        br
        h4.font-weight-200
          = date.strftime('%A')
      
      ul.text-black
        br
        - for meeting in meetings
          h3
            .text-center
              = link_to meeting.name, meeting_path(meeting)
          table.white-borders.text-left
            tr.white-borders
              td.width-100
                | Start time:
              td = meeting.start_time.strftime("%d.%m.%Y")
            - if meeting.end_time != nil
              tr.white-borders
                td.width-100
                  | End time:
                td = meeting.end_time.strftime("%d.%m.%Y")
            - if meeting.place != '' && meeting.place != nil
              tr.white-borders
                td.width-100 valign="top"
                  | Place:
                td.text-left = truncate(meeting.place, length: 90, separator: ' ')
            - if meeting.description != ''
              tr.white-borders
                td.width-100 valign="top"
                  | Description:
                td = truncate(meeting.description, length: 90, separator: ' ')
            tr.white-borders
              td.width-100 valign="top"
                | Autor:
              td
                dfn
                  = link_to meeting.user.email, user_show_path(meeting.user)
          .text-center
            = link_to "Show", meeting_path(meeting), class: "hollow button"
          hr
          br
        - if meetings.empty?
          h5.text-center.font-weight-200
            | No events
      h4.font-weight-200
        i
          = link_to "Create event on this day", new_meeting_path(start_date: date.strftime("%d.%m.%Y"))
  .small-2.columns
    h4.text-center.font-weight-200
      | My events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", meetings_path
      .font-weight-300 
        = link_to "Day calendar", day_calendar_meetings_path
      = link_to "List", list_meetings_path
      hr
      = link_to "Today", day_calendar_meetings_path

app/views/meetings/edit.html.slim
h3
  .text-center
    | Editing event
= render 'form'

app/views/meetings/index.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = month_calendar events: @meetings do |date, meetings|
      .text-right
        - if date == Date.today
          = link_to date.strftime("%d"), day_calendar_meetings_path(start_date: date.strftime("%Y-%m-%d")), {style: 'color: red'}
        - else
          = link_to date.strftime("%d"), day_calendar_meetings_path(start_date: date.strftime("%Y-%m-%d"))
      ul
        .text-black
          - if meetings != nil
            - for meeting in meetings
              li
                = link_to truncate(meeting.name, length: 9, separator: ' '), meeting_path(meeting)
  .small-2.columns
    h4.text-center.font-weight-200
      | My events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200
      .font-weight-300 
        = link_to "Month calendar", meetings_path
      = link_to "Day calendar", day_calendar_meetings_path
      br
      = link_to "List", list_meetings_path
      hr
      = link_to "Today", meetings_path

app/views/meetings/list.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    - for meeting in @meetings
      - if params[:today_events] == 'true'
        - if meeting.start_time == Date.today
          h3.text-center
            = link_to meeting.name, meeting_path(meeting)
          table.white-borders
            tr
              td.width-100
                | Start time:
              td = meeting.start_time.strftime("%d.%m.%Y")
            - if meeting.end_time != nil
              tr
                td.width-100
                  | End time:
                td = meeting.end_time.strftime("%d.%m.%Y")
            - if meeting.place != '' && meeting.place != nil
              tr
                td.width-100 valign="top"
                  | Place:
                td = truncate(meeting.place, length: 90, separator: ' ')
            - if meeting.description != ''
              tr
                td.width-100 valign="top"
                  | Description:
                td = truncate(meeting.description, length: 90, separator: ' ')
            tr
              td.width-100 valign="top"
                | Autor:
              td
                dfn
                  = link_to meeting.user.email, user_show_path(meeting.user)
          hr
      - else
        h3.text-center
          = link_to meeting.name, meeting_path(meeting)
        table.white-borders
          tr
            td.width-100
              | Start time:
            td = meeting.start_time.strftime("%d.%m.%Y")
          - if meeting.end_time != nil
            tr
              td.width-100
                | End time:
              td = meeting.end_time.strftime("%d.%m.%Y")
          - if meeting.place != '' && meeting.place != nil
            tr
              td.width-100 valign="top"
                | Place:
              td = truncate(meeting.place, length: 90, separator: ' ')
          - if meeting.description != ''
            tr
              td.width-100 valign="top"
                | Description:
              td = truncate(meeting.description, length: 90, separator: ' ')
          tr
            td.width-100 valign="top"
              | Autor:
            td
              dfn
                = link_to meeting.user.email, user_show_path(meeting.user)
        hr
    = paginate @meetings
    - if @meetings.empty?
      h2.text-center
        | All events
      h3.text-center
        br
          | No events. You can  
          dfn
            = link_to "create", new_meeting_path
          |  an event first
    
  .small-2.columns
    h4.text-center.font-weight-200
      | My events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", meetings_path
      br
      = link_to "Day calendar", day_calendar_meetings_path
      .font-weight-300 
        = link_to "List", list_meetings_path
      hr
      - if params[:today_events] == 'true'
        = link_to "All events", list_meetings_path(today_events: false)
      - else
        = link_to "Events today", list_meetings_path(today_events: true)

app/views/meetings/show.html.slim
.row
  .small-6.small-offset-3.columns
    div id="notice"
      = notice

    h2
      .text-center
        = @meeting.name
    table.white-borders
      tr
        td.width-100
          | Start time:
        td = @meeting.start_time.strftime("%d.%m.%Y")
      - if @meeting.end_time != nil
        tr
          td.width-100
            | End time:
          td = @meeting.end_time.strftime("%d.%m.%Y")
      - if @meeting.place != '' && @meeting.place != nil
        tr
          td.width-100 valign="top"
            | Place:
          td = @meeting.place
      - if @meeting.description != ''
        tr
          td.width-100 valign="top"
            | Description:
          td = @meeting.description
      tr
        td.width-100 valign="top"
          | Autor:
        td
          dfn
            = link_to @meeting.user.email, user_show_path(@meeting.user)
    br
    .text-center
      = link_to 'Edit', edit_meeting_path(@meeting), class: "button"
      |  
      = link_to 'Destroy', meeting_path, method: :delete, class: "hollow button alert"
      |  
      = link_to 'Back', :back , class: "hollow button"

app/views/user_meetings/day_calendar.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = calendar number_of_days: 1, events: @meetings do |date, meetings|
      - if date == Date.today
        .text-red
          = date.strftime("%d")
          |  
          = date.strftime("%B")
          |  
          = date.strftime("%Y")
          br
          h4.font-weight-200.padding-top-8
            = date.strftime('%A')
      - else
        = date.strftime("%d")
        |  
        = date.strftime("%B")
        |  
        = date.strftime("%Y")
        br
        h4.font-weight-200
          = date.strftime('%A')
      
      ul.text-black
        br
        - for meeting in meetings
          h3
            .text-center
              = link_to meeting.name, meeting_path(meeting)
          table.white-borders.text-left
            tr.white-borders
              td.width-100
                | Start time:
              td = meeting.start_time.strftime("%d.%m.%Y")
            - if meeting.end_time != nil
              tr.white-borders
                td.width-100
                  | End time:
                td = meeting.end_time.strftime("%d.%m.%Y")
            - if meeting.place != '' && meeting.place != nil
              tr.white-borders
                td.width-100 valign="top"
                  | Place:
                td.text-left = truncate(meeting.place, length: 90, separator: ' ')
            - if meeting.description != ''
              tr.white-borders
                td.width-100 valign="top"
                  | Description:
                td = truncate(meeting.description, length: 90, separator: ' ')
            tr.white-borders
              td.width-100 valign="top"
                | Autor:
              td
                dfn
                  = link_to meeting.user.email, user_show_path(meeting.user)
          .text-center
            = link_to "Show", meeting_path(meeting), class: "hollow button"
          hr
          br
        - if meetings.empty?
          h5.text-center.font-weight-200
            | No events
  .small-2.columns
    h4.text-center.font-weight-200
      dfn
        = link_to @user.first_name, user_show_path(@user)
        |  
        = link_to @user.second_name, user_show_path(@user)
      | 's events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", user_meetings_path('id': @user.id)
      .font-weight-300 
        = link_to "Day calendar", day_calendar_user_meetings_path('id': @user.id)
      = link_to "List", list_user_meetings_path('id': @user.id)
      hr
      = link_to "Today", day_calendar_user_meetings_path('id': @user.id)

app/views/user_meetings/index.html.slim
== yield

.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    = month_calendar events: @meetings do |date, meetings|
      .text-right
        - if date == Date.today
          = link_to date.strftime("%d"), day_calendar_user_meetings_path(id: @user.id, start_date: date.strftime("%Y-%m-%d")), {style: 'color: red'}
        - else
          = link_to date.strftime("%d"), day_calendar_user_meetings_path(id: @user.id, start_date: date.strftime("%Y-%m-%d"))
      
      ul
        .text-black
          - if meetings != nil
            - for meeting in meetings
              - if meeting.user_id == current_user.id
                li
                  = link_to truncate(meeting.name, length: 9, separator: ' '), {controller: "meetings", action: "show", id: meeting.id}
              - else
                li
                  = link_to truncate(meeting.name, length: 9, separator: ' '), all_meeting_path(meeting)
  .small-2.columns
    h4.text-center.font-weight-200
      dfn
        = link_to @user.first_name, user_show_path(@user)
        |  
        = link_to @user.second_name, user_show_path(@user)
      | 's events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200
      .font-weight-300 
        = link_to "Month calendar", user_meetings_path('id': @user.id)
      = link_to "Day calendar", day_calendar_user_meetings_path('id': @user.id)
      br
      = link_to "List", list_user_meetings_path('id': @user.id)
      hr
      = link_to "Today", user_meetings_path('id': @user.id)

app/views/user_meetings/list.html.slim
== yield
.row
  .small-8.small-offset-2.columns
    br
    div id="notice"
      = notice

    - for meeting in @meetings
      - if params[:today_events] == 'true'
        - if meeting.start_time == Date.today
          h3.text-center
            = link_to meeting.name, all_meeting_path(meeting)
          table.white-borders
            tr
              td.width-100
                | Start time:
              td = meeting.start_time.strftime("%d.%m.%Y")
            - if meeting.end_time != nil
              tr
                td.width-100
                  | End time:
                td = meeting.end_time.strftime("%d.%m.%Y")
            - if meeting.place != '' && meeting.place != nil
              tr
                td.width-100 valign="top"
                  | Place:
                td = truncate(meeting.place, length: 90, separator: ' ')
            - if meeting.description != ''
              tr
                td.width-100 valign="top"
                  | Description:
                td = truncate(meeting.description, length: 90, separator: ' ')
            tr
              td.width-100 valign="top"
                | Autor:
              td
                dfn
                  = link_to meeting.user.email, user_show_path(meeting.user)
          hr
      - else
        h3.text-center
          = link_to meeting.name, all_meeting_path(meeting)
        table.white-borders
          tr
            td.width-100
              | Start time:
            td = meeting.start_time.strftime("%d.%m.%Y")
          - if meeting.end_time != nil
            tr
              td.width-100
                | End time:
              td = meeting.end_time.strftime("%d.%m.%Y")
          - if meeting.place != '' && meeting.place != nil
            tr
              td.width-100 valign="top"
                | Place:
              td = truncate(meeting.place, length: 90, separator: ' ')
          - if meeting.description != ''
            tr
              td.width-100 valign="top"
                | Description:
              td = truncate(meeting.description, length: 90, separator: ' ')
          tr
            td.width-100 valign="top"
              | Autor:
            td
              dfn
                = link_to meeting.user.email, user_show_path(meeting.user)
        hr

    = paginate @meetings
    - if @meetings.empty?
      h2.text-center
        dfn
          = link_to @user.first_name, user_show_path(@user)
          |  
          = link_to @user.second_name, user_show_path(@user)
        | 's events
      h3.text-center
        br
        dfn
          = link_to @user.first_name, user_show_path(@user)
          |  
          = link_to @user.second_name, user_show_path(@user)
        |  has not created events yet
  .small-2.columns
    h4.text-center.font-weight-200
      dfn
        = link_to @user.first_name, user_show_path(@user)
        |  
        = link_to @user.second_name, user_show_path(@user)
      | 's events (
      = @meetings.size
      | )
    hr
    h5.font-weight-200 
      = link_to "Month calendar", user_meetings_path('id': @user.id)
      br
      = link_to "Day calendar", day_calendar_user_meetings_path('id': @user.id)
      .font-weight-300
        = link_to "List", list_user_meetings_path('id': @user.id)
      hr
      - if params[:today_events] == 'true'
        = link_to "All events", list_user_meetings_path('id': @user.id, today_events: false)
      - else
        = link_to "Events today", list_user_meetings_path('id': @user.id, today_events: true)